### ISSUE TITLE
发现少了一个非洲国家

### ISSUE THREAD

**Issue by jialechan** [jjeejj/CountryCodeAndPhoneCode#2]
{
        "english_name":"The Democratic Republic of the Congo",
        "chinese_name":"刚果民主共和国",
        "country_code":"CD",
        "phone_code":"243"
    },

**Comment by jjeejj** [comment]
@jialechan  哪个平台下的？ 我去检查下

**Comment by jialechan** [comment]
https://github.com/jjeejj/CountryCodeAndPhoneCode/blob/master/all/countryCodeAndPhoneCode.json

**Comment by jjeejj** [comment]
@jialechan  有在对应的短信平台看到支持这个国家了吗？

**Comment by jjeejj** [comment]
存在的，可以根据 【刚果民主共和国】 查询
